### ISSUE TITLE
Nonplaying audio in windows

### ISSUE THREAD

**Issue by emperor-limitless** [Edgaru089/audio#1]
Hi
Just started wanting to try this package today, Using windows, However, When trying the example, With a valid flac file and the openal32.dll file being at the same place of the executable, It does not work, It doesn't panic, But audio doesn't play.
I even tried using wav or ogg, But nothing else works, Am I missing something or is this package not ready for usidge in windows yet?
Thanks.

**Comment by Edgaru089** [comment]
Did you call `audio.Init()` in the main function? I forgot to mention that in the README, my bad.

If this still does not work, would you provide some detailed information (go version, gcc version, etc) so that I can replicate your problem.

**Comment by emperor-limitless** [comment]
Works, Thanks, I was searching for something like this package for a long time.
