### ISSUE TITLE
Could loading from []bytes be implemented for music and buffer?

### ISSUE THREAD

**Issue by emperor-limitless** [Edgaru089/audio#2]
Hi

Could loading from []byte be added to buffer and music?

This is really useful for when one wants to load audio from encrypted data for example after decrypting.

Thanks.

**Comment by Edgaru089** [comment]
If you're talking about files loaded into memory, you can use ```bytes.NewReader()``` provided by the Go standard library to create a ```io.ReadSeeker``` from a byte slice.

As for raw PCM data in memory, well that's a bit tricky. I can implement that but the use case is quite narrow to be honest...

**Comment by emperor-limitless** [comment]
Thanks, bytes.NewReader works.
