### ISSUE TITLE
Could the ability to make audio loop be added?

### ISSUE THREAD

**Issue by emperor-limitless** [Edgaru089/audio#3]
Hi

Could the ability for audio to be looped, Keep playing endlessly until the program stops/the handle getting destroyed be added?

**Comment by Edgaru089** [comment]
Well this is quite complicated. SFML (by which most of this package is inspired) has a `Music` class with looping support that's, well, quite complicated and not elegant. So, upon writing the `SoundStream` part I decided to ditch it completely.

If you don't care about seeking and telling the playback position, you can write your own [`audio.SoundStreamInterface`](https://github.com/Edgaru089/audio/blob/master/stream.go#L19) with a empty `Seek` method that provides samples from, e.g., a `SoundBuffer`, in a looped manner.

If you do care, however, this is far too complicated and way beyond my abilities...

**Comment by emperor-limitless** [comment]
Alright, Will try that, Thanks.
